import{a as S,S as q,i as a}from"./assets/vendor-73qhTu8_.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const P="55702648-64b3acfb28daf85718edb0503",B="https://pixabay.com/api/";async function f(o,r){return(await S.get(B,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const r=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:t,views:n,comments:v,downloads:w})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${s}" alt="${e}" loading="lazy"/>
        </a>
        <div class="info">
          <p><b>Likes</b> ${t}</p>
          <p><b>Views</b> ${n}</p>
          <p><b>Comments</b> ${v}</p>
          <p><b>Downloads</b> ${w}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),$.refresh()}function E(){m.innerHTML=""}function h(){p.classList.add("visible")}function b(){p.classList.remove("visible")}function M(){y.classList.add("visible")}function L(){y.classList.remove("visible")}const d=document.querySelector(".form"),R=document.querySelector(".load-more");let l="",i=1,u=0;d.addEventListener("submit",async o=>{o.preventDefault();const r=d.elements["search-text"].value.trim();if(r){l=r,i=1,E(),L(),h();try{const s=await f(l,i);if(u=s.totalHits,s.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(s.hits),i*15<u?M():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(s){a.error({message:"Something went wrong. Please try again!",position:"topRight"}),console.error(s)}finally{b()}}});R.addEventListener("click",async()=>{i+=1,h();try{const o=await f(l,i);g(o.hits);const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),i*15>=u&&(L(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){a.error({message:"Something went wrong. Please try again!",position:"topRight"}),console.error(o)}finally{b()}});
//# sourceMappingURL=index.js.map
